// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// DO NOT EDIT - This file is generated by gen_lang_imports through the gen-lang-imports script

/* eslint-disable */

import fa from './fa.json';

type TranslationsMap = {
    [id: string]: string,
};

export const langIDs = ["fa"];

export const langLabels = {"fa":"فارسی"};

export const langFiles: {[langID: string]: TranslationsMap} = {fa};